

GET http://localhost:5180/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJHYW5kYSIsImVtYWlsIjoiZ2FuZGFAZ21haWwuY29tIiwiaWF0IjoxNzM1Nzg5Njk0LCJleHAiOjE3MzU3ODk3MTR9.Yz0R8JM9JEZHsd4OxVBGUPAaDW5NOt9dfBUOEe8n1lE

###
POST http://localhost:5180/users
Content-Type: application/json

{
    "name": "Ganda",
    "email": "ganda2@gmail.com",
    "password": "123456",
    "confPassword": "123456"
} 

###
POST http://localhost:5180/login
Content-Type: application/json

{
    "email": "ganda@gmail.com",
    "password": "123456"
    
} 
###
GET http://localhost:5180/token


###
DELETE http://localhost:5180/logout